export interface ExchangeInfo {
  id: string;
  name: string;
  complianceEmail: string;
  legalEmail?: string;
  responseTime: string; // e.g. "7-14 days"
  notes: string;
  region: string;
  kycLevel: 'strict' | 'moderate' | 'minimal';
  /** Whether a subpoena/court order is typically required for account holder info */
  requiresSubpoena: boolean;
  /** Whether the exchange is still operational */
  active: boolean;
  website: string;
}

export const EXCHANGES: ExchangeInfo[] = [
  {
    id: 'binance',
    name: 'Binance',
    complianceEmail: 'compliance@binance.com',
    legalEmail: 'law-enforcement@binance.com',
    responseTime: '7-14 days',
    notes: 'Largest global exchange. Has dedicated Law Enforcement Response Team. Preservation requests processed faster with police report reference.',
    region: 'Global',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.binance.com',
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    complianceEmail: 'compliance@coinbase.com',
    legalEmail: 'legalprocess@coinbase.com',
    responseTime: '10-21 days',
    notes: 'US-regulated, publicly traded (NASDAQ: COIN). Strong compliance department. Responds to valid legal process from US law enforcement. Has a Law Enforcement Portal.',
    region: 'US / Global',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.coinbase.com',
  },
  {
    id: 'kraken',
    name: 'Kraken',
    complianceEmail: 'compliance@kraken.com',
    legalEmail: 'legalprocess@kraken.com',
    responseTime: '10-14 days',
    notes: 'US-based exchange with strong KYC. Responds to valid subpoenas. Has published transparency reports.',
    region: 'US / Global',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.kraken.com',
  },
  {
    id: 'okx',
    name: 'OKX',
    complianceEmail: 'compliance@okx.com',
    legalEmail: 'lawenforcement@okx.com',
    responseTime: '7-14 days',
    notes: 'Global exchange with compliance team. Responds to law enforcement requests. Include police report number for faster processing.',
    region: 'Global',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.okx.com',
  },
  {
    id: 'bybit',
    name: 'Bybit',
    complianceEmail: 'compliance@bybit.com',
    legalEmail: 'lawenforcement@bybit.com',
    responseTime: '7-14 days',
    notes: 'Dubai-based exchange. Has compliance department. Include case reference and police report.',
    region: 'Global',
    kycLevel: 'moderate',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.bybit.com',
  },
  {
    id: 'kucoin',
    name: 'KuCoin',
    complianceEmail: 'support@kucoin.com',
    legalEmail: 'law@kucoin.com',
    responseTime: '14-21 days',
    notes: 'Seychelles-based. Response times can be longer. Police report strongly recommended.',
    region: 'Global',
    kycLevel: 'moderate',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.kucoin.com',
  },
  {
    id: 'gateio',
    name: 'Gate.io',
    complianceEmail: 'compliance@gate.io',
    legalEmail: 'law@gate.io',
    responseTime: '14-21 days',
    notes: 'Cayman Islands registered. May require formal legal process for account disclosure.',
    region: 'Global',
    kycLevel: 'moderate',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.gate.io',
  },
  {
    id: 'htx',
    name: 'HTX (Huobi)',
    complianceEmail: 'compliance@huobi.com',
    legalEmail: 'lawenforcement@htx.com',
    responseTime: '14-21 days',
    notes: 'Formerly Huobi, now HTX. Seychelles-based. Response times vary. Include police report.',
    region: 'Global',
    kycLevel: 'moderate',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.htx.com',
  },
  {
    id: 'cryptocom',
    name: 'Crypto.com',
    complianceEmail: 'compliance@crypto.com',
    legalEmail: 'lawenforcement@crypto.com',
    responseTime: '10-14 days',
    notes: 'Singapore-based, strong compliance. Has dedicated law enforcement cooperation team.',
    region: 'Global',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://crypto.com',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    complianceEmail: 'compliance@gemini.com',
    legalEmail: 'legalprocess@gemini.com',
    responseTime: '7-14 days',
    notes: 'New York regulated (NYDFS BitLicense). Strong compliance. Responds to valid legal process promptly.',
    region: 'US',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.gemini.com',
  },
  {
    id: 'bitstamp',
    name: 'Bitstamp',
    complianceEmail: 'compliance@bitstamp.net',
    legalEmail: 'legal@bitstamp.net',
    responseTime: '10-14 days',
    notes: 'Luxembourg-based, one of oldest exchanges. Strong European regulatory compliance.',
    region: 'EU / Global',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.bitstamp.net',
  },
  {
    id: 'bitfinex',
    name: 'Bitfinex',
    complianceEmail: 'compliance@bitfinex.com',
    legalEmail: 'legalprocess@bitfinex.com',
    responseTime: '14-21 days',
    notes: 'BVI-based. Related to Tether. Has compliance team but response may be slower.',
    region: 'Global',
    kycLevel: 'moderate',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.bitfinex.com',
  },
  {
    id: 'poloniex',
    name: 'Poloniex',
    complianceEmail: 'compliance@poloniex.com',
    responseTime: '21-30 days',
    notes: 'Now owned by Justin Sun. Response times may be longer. Regulatory standing uncertain.',
    region: 'Global',
    kycLevel: 'minimal',
    requiresSubpoena: true,
    active: true,
    website: 'https://poloniex.com',
  },
  {
    id: 'mexc',
    name: 'MEXC',
    complianceEmail: 'compliance@mexc.com',
    legalEmail: 'law@mexc.com',
    responseTime: '14-21 days',
    notes: 'Singapore-based. Growing compliance program. Include police report for better response.',
    region: 'Global',
    kycLevel: 'moderate',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.mexc.com',
  },
  {
    id: 'phemex',
    name: 'Phemex',
    complianceEmail: 'compliance@phemex.com',
    responseTime: '14-21 days',
    notes: 'Singapore-based derivatives exchange. Include case reference and police report.',
    region: 'Global',
    kycLevel: 'moderate',
    requiresSubpoena: true,
    active: true,
    website: 'https://phemex.com',
  },
  {
    id: 'deribit',
    name: 'Deribit',
    complianceEmail: 'compliance@deribit.com',
    responseTime: '14-21 days',
    notes: 'Panama-based derivatives exchange. Focused on options/futures. Smaller user base.',
    region: 'Global',
    kycLevel: 'moderate',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.deribit.com',
  },
  {
    id: 'bitmex',
    name: 'BitMEX',
    complianceEmail: 'compliance@bitmex.com',
    legalEmail: 'lawenforcement@bitmex.com',
    responseTime: '14-21 days',
    notes: 'Seychelles-based derivatives platform. Implemented KYC after regulatory pressure.',
    region: 'Global',
    kycLevel: 'moderate',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.bitmex.com',
  },
  {
    id: 'upbit',
    name: 'Upbit',
    complianceEmail: 'compliance@upbit.com',
    responseTime: '14-21 days',
    notes: 'South Korea largest exchange. Strict Korean KYC (real-name verification). Korean language requests preferred.',
    region: 'South Korea',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://upbit.com',
  },
  {
    id: 'bithumb',
    name: 'Bithumb',
    complianceEmail: 'compliance@bithumb.com',
    responseTime: '14-21 days',
    notes: 'Major Korean exchange. Korean KYC requirements. May require Korean law enforcement involvement.',
    region: 'South Korea',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://www.bithumb.com',
  },
  {
    id: 'coincheck',
    name: 'Coincheck',
    complianceEmail: 'compliance@coincheck.com',
    responseTime: '14-21 days',
    notes: 'Japanese FSA-regulated exchange. Acquired by Monex Group. Japanese law enforcement requests processed faster.',
    region: 'Japan',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://coincheck.com',
  },
  {
    id: 'bitflyer',
    name: 'bitFlyer',
    complianceEmail: 'compliance@bitflyer.com',
    responseTime: '14-21 days',
    notes: 'Japanese FSA-regulated. Has US and EU presence. Strong regulatory compliance across jurisdictions.',
    region: 'Japan / US / EU',
    kycLevel: 'strict',
    requiresSubpoena: true,
    active: true,
    website: 'https://bitflyer.com',
  },
  {
    id: 'ftx',
    name: 'FTX',
    complianceEmail: 'claims@ftx.com',
    responseTime: 'Unknown',
    notes: 'BANKRUPT — Filed Chapter 11 (Nov 2022). No active trading. Claims process managed by bankruptcy estate. Contact the FTX Claims Portal for asset recovery.',
    region: 'N/A (Bankrupt)',
    kycLevel: 'strict',
    requiresSubpoena: false,
    active: false,
    website: 'https://claims.ftx.com',
  },
  {
    id: 'changenow',
    name: 'ChangeNOW',
    complianceEmail: 'compliance@changenow.io',
    responseTime: '14-30 days',
    notes: 'Non-custodial swap service. Limited KYC. May be difficult to obtain user info. Include transaction IDs.',
    region: 'Global',
    kycLevel: 'minimal',
    requiresSubpoena: true,
    active: true,
    website: 'https://changenow.io',
  },
  {
    id: 'fixedfloat',
    name: 'FixedFloat',
    complianceEmail: 'support@fixedfloat.com',
    responseTime: '21-30 days',
    notes: 'Non-custodial swap. Minimal KYC. Cooperation with law enforcement varies. Formal legal process recommended.',
    region: 'Global',
    kycLevel: 'minimal',
    requiresSubpoena: true,
    active: true,
    website: 'https://fixedfloat.com',
  },
];

export const EXCHANGE_MAP = new Map(EXCHANGES.map((e) => [e.id, e]));

export function getExchangeById(id: string): ExchangeInfo | undefined {
  return EXCHANGE_MAP.get(id);
}

export function getActiveExchanges(): ExchangeInfo[] {
  return EXCHANGES.filter((e) => e.active);
}

export const NETWORKS = [
  { id: 'eth', label: 'Ethereum (ETH)' },
  { id: 'btc', label: 'Bitcoin (BTC)' },
  { id: 'sol', label: 'Solana (SOL)' },
  { id: 'trx', label: 'TRON (TRX)' },
  { id: 'bnb', label: 'BNB Chain (BNB)' },
  { id: 'polygon', label: 'Polygon (MATIC)' },
  { id: 'base', label: 'Base' },
  { id: 'arb', label: 'Arbitrum' },
  { id: 'op', label: 'Optimism' },
  { id: 'avax', label: 'Avalanche (AVAX)' },
  { id: 'linea', label: 'Linea' },
  { id: 'zksync', label: 'zkSync Era' },
  { id: 'scroll', label: 'Scroll' },
  { id: 'mantle', label: 'Mantle' },
] as const;
