import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { ReportData } from './generateReport';

const blue = '#2563eb';
const slate900 = '#0f172a';
const slate600 = '#475569';
const slate400 = '#94a3b8';
const red = '#dc2626';
const green = '#16a34a';
const amber = '#d97706';

const s = StyleSheet.create({
  page: { padding: 50, fontFamily: 'Helvetica', fontSize: 10, color: slate900 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#e2e8f0' },
  logo: { fontSize: 16, fontFamily: 'Helvetica-Bold', color: blue },
  headerRight: { textAlign: 'right', fontSize: 8, color: slate400 },
  footer: { position: 'absolute', bottom: 30, left: 50, right: 50, flexDirection: 'row', justifyContent: 'space-between', fontSize: 7, color: slate400, borderTopWidth: 1, borderTopColor: '#e2e8f0', paddingTop: 8 },
  h1: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: slate900, marginBottom: 6 },
  h2: { fontSize: 16, fontFamily: 'Helvetica-Bold', color: slate900, marginBottom: 10, marginTop: 4 },
  h3: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: slate900, marginBottom: 6 },
  p: { fontSize: 10, color: slate600, lineHeight: 1.5, marginBottom: 8 },
  label: { fontSize: 8, color: slate400, marginBottom: 2 },
  value: { fontSize: 14, fontFamily: 'Helvetica-Bold', color: slate900 },
  row: { flexDirection: 'row', gap: 16 },
  col: { flex: 1 },
  card: { backgroundColor: '#f8fafc', borderRadius: 6, padding: 12, marginBottom: 8 },
  table: { marginTop: 4 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f1f5f9', paddingVertical: 6, paddingHorizontal: 8, borderRadius: 4 },
  tableRow: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, borderBottomWidth: 0.5, borderBottomColor: '#e2e8f0' },
  th: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: slate600 },
  td: { fontSize: 8, color: slate900 },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, fontSize: 10, fontFamily: 'Helvetica-Bold' },
  bullet: { fontSize: 10, color: slate600, lineHeight: 1.5, marginBottom: 4, paddingLeft: 12 },
  mono: { fontFamily: 'Courier', fontSize: 8 },
  divider: { borderBottomWidth: 1, borderBottomColor: '#e2e8f0', marginVertical: 16 },
});

const Header = ({ data }: { data: ReportData }) => (
  <View style={s.header}>
    <Text style={s.logo}>LedgerHound</Text>
    <View style={s.headerRight}>
      <Text>Case ID: {data.caseId}</Text>
      <Text>{data.date}</Text>
    </View>
  </View>
);

const Footer = ({ data }: { data: ReportData }) => (
  <View style={s.footer} fixed>
    <Text>LedgerHound · USPROJECT LLC · Confidential</Text>
    <Text>{data.caseId}</Text>
  </View>
);

const shortAddr = (addr: string) => `${addr.slice(0, 8)}...${addr.slice(-6)}`;

const riskColor = (score: number) => {
  if (score >= 70) return red;
  if (score >= 40) return amber;
  return green;
};

// Page 1: Cover
const CoverPage = ({ data }: { data: ReportData }) => (
  <Page size="A4" style={{ ...s.page, justifyContent: 'center', alignItems: 'center' }}>
    <View style={{ alignItems: 'center' }}>
      <Text style={{ fontSize: 28, fontFamily: 'Helvetica-Bold', color: blue, marginBottom: 40 }}>LedgerHound</Text>
      <Text style={{ fontSize: 20, fontFamily: 'Helvetica-Bold', color: slate900, marginBottom: 6 }}>FORENSIC WALLET</Text>
      <Text style={{ fontSize: 20, fontFamily: 'Helvetica-Bold', color: slate900, marginBottom: 30 }}>ANALYSIS REPORT</Text>
      <View style={{ backgroundColor: '#f1f5f9', borderRadius: 8, padding: 20, width: 400, alignItems: 'center', marginBottom: 30 }}>
        <Text style={{ fontSize: 8, color: slate400, marginBottom: 4 }}>WALLET ADDRESS</Text>
        <Text style={{ fontFamily: 'Courier', fontSize: 10, color: slate900 }}>{data.walletAddress}</Text>
      </View>
      <View style={s.row}>
        <View style={{ alignItems: 'center', marginRight: 40 }}>
          <Text style={s.label}>DATE</Text>
          <Text style={{ fontSize: 12, fontFamily: 'Helvetica-Bold' }}>{data.date}</Text>
        </View>
        <View style={{ alignItems: 'center' }}>
          <Text style={s.label}>CASE ID</Text>
          <Text style={{ fontSize: 12, fontFamily: 'Helvetica-Bold' }}>{data.caseId}</Text>
        </View>
      </View>
      <Text style={{ fontSize: 10, color: red, fontFamily: 'Helvetica-Bold', marginTop: 40 }}>CONFIDENTIAL — For Legal Use</Text>
      <Text style={{ fontSize: 8, color: slate400, marginTop: 20 }}>Generated by LedgerHound · USPROJECT LLC</Text>
    </View>
  </Page>
);

// Page 2: Executive Summary
const SummaryPage = ({ data }: { data: ReportData }) => (
  <Page size="A4" style={s.page}>
    <Header data={data} />
    <Text style={s.h2}>Executive Summary</Text>

    <View style={{ ...s.card, alignItems: 'center', marginBottom: 16 }}>
      <Text style={s.label}>RISK SCORE</Text>
      <Text style={{ fontSize: 36, fontFamily: 'Helvetica-Bold', color: riskColor(data.riskScore) }}>{data.riskScore}</Text>
      <Text style={{ ...s.badge, backgroundColor: riskColor(data.riskScore), color: 'white' }}>{data.riskLabel}</Text>
    </View>

    <Text style={s.h3}>Key Findings</Text>
    {data.keyFindings.map((f, i) => (
      <Text key={i} style={s.bullet}>• {f}</Text>
    ))}

    <View style={s.divider} />

    <Text style={s.h3}>Recommended Actions</Text>
    {data.recommendations.map((r, i) => (
      <Text key={i} style={s.bullet}>{i + 1}. {r}</Text>
    ))}

    <Footer data={data} />
  </Page>
);

// Page 3: Wallet Analytics
const AnalyticsPage = ({ data }: { data: ReportData }) => (
  <Page size="A4" style={s.page}>
    <Header data={data} />
    <Text style={s.h2}>Wallet Analytics</Text>

    <View style={{ ...s.row, marginBottom: 12 }}>
      <View style={{ ...s.card, ...s.col }}>
        <Text style={s.label}>TOTAL RECEIVED</Text>
        <Text style={{ ...s.value, color: green }}>{data.totalReceived} ETH</Text>
      </View>
      <View style={{ ...s.card, ...s.col }}>
        <Text style={s.label}>TOTAL SENT</Text>
        <Text style={{ ...s.value, color: red }}>{data.totalSent} ETH</Text>
      </View>
      <View style={{ ...s.card, ...s.col }}>
        <Text style={s.label}>NET BALANCE</Text>
        <Text style={s.value}>{data.netBalance} ETH</Text>
      </View>
    </View>

    <View style={{ ...s.row, marginBottom: 16 }}>
      <View style={{ ...s.card, ...s.col }}>
        <Text style={s.label}>TRANSACTIONS</Text>
        <Text style={s.value}>{data.transactionCount}</Text>
      </View>
      <View style={{ ...s.card, ...s.col }}>
        <Text style={s.label}>ACTIVE PERIOD</Text>
        <Text style={{ fontSize: 10, fontFamily: 'Helvetica-Bold' }}>{data.firstActivity} — {data.lastActivity}</Text>
      </View>
      <View style={{ ...s.card, ...s.col }}>
        <Text style={s.label}>UNIQUE TOKENS</Text>
        <Text style={s.value}>{data.uniqueTokens.length}</Text>
      </View>
    </View>

    <Text style={s.h3}>Top 5 Counterparty Addresses</Text>
    <View style={s.table}>
      <View style={s.tableHeader}>
        <Text style={{ ...s.th, width: '40%' }}>Address</Text>
        <Text style={{ ...s.th, width: '20%' }}>Entity</Text>
        <Text style={{ ...s.th, width: '20%' }}>Interactions</Text>
        <Text style={{ ...s.th, width: '20%' }}>Volume (ETH)</Text>
      </View>
      {data.topCounterparties.map((cp, i) => (
        <View key={i} style={s.tableRow}>
          <Text style={{ ...s.td, ...s.mono, width: '40%' }}>{shortAddr(cp.address)}</Text>
          <Text style={{ ...s.td, width: '20%' }}>{cp.label}</Text>
          <Text style={{ ...s.td, width: '20%' }}>{cp.count}</Text>
          <Text style={{ ...s.td, width: '20%' }}>{cp.volume.toFixed(4)}</Text>
        </View>
      ))}
    </View>

    <Footer data={data} />
  </Page>
);

// Page 4: Entity Identification
const EntitiesPage = ({ data }: { data: ReportData }) => (
  <Page size="A4" style={s.page}>
    <Header data={data} />
    <Text style={s.h2}>Entity Identification</Text>

    {data.identifiedEntities.length === 0 ? (
      <View style={s.card}>
        <Text style={s.p}>No known entities identified in automated analysis. This does not mean the addresses are unrelated to known entities — manual investigation with commercial tools may reveal additional attributions.</Text>
      </View>
    ) : (
      <View style={s.table}>
        <View style={s.tableHeader}>
          <Text style={{ ...s.th, width: '35%' }}>Address</Text>
          <Text style={{ ...s.th, width: '25%' }}>Entity</Text>
          <Text style={{ ...s.th, width: '20%' }}>Type</Text>
          <Text style={{ ...s.th, width: '20%' }}>Interactions</Text>
        </View>
        {data.identifiedEntities.map((e, i) => (
          <View key={i} style={{ ...s.tableRow, backgroundColor: e.type === 'mixer' ? '#fef2f2' : e.type === 'exchange' ? '#f0fdf4' : undefined }}>
            <Text style={{ ...s.td, ...s.mono, width: '35%' }}>{shortAddr(e.address)}</Text>
            <Text style={{ ...s.td, width: '25%', fontFamily: 'Helvetica-Bold' }}>{e.label}</Text>
            <Text style={{ ...s.td, width: '20%', color: e.type === 'mixer' ? red : e.type === 'exchange' ? green : slate600 }}>{e.type.toUpperCase()}</Text>
            <Text style={{ ...s.td, width: '20%' }}>{e.interactions}</Text>
          </View>
        ))}
      </View>
    )}

    {data.identifiedEntities.some((e) => e.type === 'mixer') && (
      <View style={{ backgroundColor: '#fef2f2', borderRadius: 6, padding: 12, marginTop: 16 }}>
        <Text style={{ fontSize: 10, fontFamily: 'Helvetica-Bold', color: red, marginBottom: 4 }}>WARNING: Mixer Activity Detected</Text>
        <Text style={{ fontSize: 9, color: slate600, lineHeight: 1.4 }}>
          This wallet has interacted with known cryptocurrency mixing services. Mixing services are commonly used to obscure the origin of funds and are associated with money laundering. Tornado Cash was sanctioned by OFAC in August 2022.
        </Text>
      </View>
    )}

    {data.identifiedEntities.some((e) => e.type === 'exchange') && (
      <View style={{ backgroundColor: '#f0fdf4', borderRadius: 6, padding: 12, marginTop: 12 }}>
        <Text style={{ fontSize: 10, fontFamily: 'Helvetica-Bold', color: green, marginBottom: 4 }}>Exchange Identified — Subpoena Target Available</Text>
        <Text style={{ fontSize: 9, color: slate600, lineHeight: 1.4 }}>
          Funds from this wallet interacted with KYC-compliant exchanges. These exchanges maintain identity records that can be obtained via legal subpoena, potentially revealing the account holder's identity.
        </Text>
      </View>
    )}

    <Footer data={data} />
  </Page>
);

// Page 5: Transaction History
const TransactionsPage = ({ data }: { data: ReportData }) => (
  <Page size="A4" style={s.page}>
    <Header data={data} />
    <Text style={s.h2}>Transaction History (Most Recent 50)</Text>

    <View style={s.table}>
      <View style={s.tableHeader}>
        <Text style={{ ...s.th, width: '14%' }}>Date</Text>
        <Text style={{ ...s.th, width: '8%' }}>Dir</Text>
        <Text style={{ ...s.th, width: '28%' }}>From</Text>
        <Text style={{ ...s.th, width: '28%' }}>To</Text>
        <Text style={{ ...s.th, width: '12%' }}>Value</Text>
        <Text style={{ ...s.th, width: '10%' }}>Token</Text>
      </View>
      {data.transactions.map((tx, i) => (
        <View key={i} style={s.tableRow}>
          <Text style={{ ...s.td, width: '14%', fontSize: 7 }}>{tx.date}</Text>
          <Text style={{ ...s.td, width: '8%', color: tx.direction === 'IN' ? green : red, fontFamily: 'Helvetica-Bold', fontSize: 7 }}>{tx.direction}</Text>
          <Text style={{ ...s.td, ...s.mono, width: '28%', fontSize: 6 }}>{shortAddr(tx.from)}</Text>
          <Text style={{ ...s.td, ...s.mono, width: '28%', fontSize: 6 }}>{shortAddr(tx.to)}</Text>
          <Text style={{ ...s.td, width: '12%', fontSize: 7 }}>{tx.value.toFixed(4)}</Text>
          <Text style={{ ...s.td, width: '10%', fontSize: 7 }}>{tx.token}</Text>
        </View>
      ))}
    </View>

    <Footer data={data} />
  </Page>
);

// Page 6: Legal Recommendations
const LegalPage = ({ data }: { data: ReportData }) => (
  <Page size="A4" style={s.page}>
    <Header data={data} />
    <Text style={s.h2}>Legal Recommendations</Text>

    {data.identifiedEntities.some((e) => e.type === 'exchange') && (
      <View style={{ ...s.card, marginBottom: 12 }}>
        <Text style={{ fontSize: 11, fontFamily: 'Helvetica-Bold', color: blue, marginBottom: 6 }}>Subpoena Target Identified</Text>
        {data.identifiedEntities.filter((e) => e.type === 'exchange').map((e, i) => (
          <Text key={i} style={{ fontSize: 10, color: slate900, marginBottom: 2 }}>
            • {e.label} ({shortAddr(e.address)}) — {e.interactions} interaction(s)
          </Text>
        ))}
        <Text style={{ fontSize: 9, color: slate600, marginTop: 8, lineHeight: 1.4 }}>
          An attorney can file a subpoena or discovery request compelling the exchange to produce account holder identification, including name, address, government ID, and banking information associated with the receiving account.
        </Text>
      </View>
    )}

    <Text style={s.h3}>Recommended Next Steps</Text>
    <Text style={s.bullet}>1. File an FBI IC3 complaint at ic3.gov if not already done.</Text>
    <Text style={s.bullet}>2. Preserve all evidence: screenshots, communications, transaction records.</Text>
    <Text style={s.bullet}>3. Consult with an attorney experienced in cryptocurrency fraud cases.</Text>
    <Text style={s.bullet}>4. Consider filing a SAR (Suspicious Activity Report) if applicable.</Text>
    {data.identifiedEntities.some((e) => e.type === 'exchange') && (
      <Text style={s.bullet}>5. Engage attorney to file emergency subpoena to identified exchange(s).</Text>
    )}
    <Text style={s.bullet}>{data.identifiedEntities.some((e) => e.type === 'exchange') ? '6' : '5'}. For comprehensive certified investigation: contact LedgerHound.</Text>

    <View style={s.divider} />

    <View style={{ ...s.card, backgroundColor: '#eff6ff' }}>
      <Text style={{ fontSize: 11, fontFamily: 'Helvetica-Bold', color: blue, marginBottom: 6 }}>Need a Certified Forensic Investigation?</Text>
      <Text style={{ fontSize: 9, color: slate600, lineHeight: 1.5 }}>
        This automated report provides a preliminary analysis based on publicly available blockchain data. For court-ready forensic investigations with certified methodology, expert testimony, and full chain-of-custody documentation, contact our forensic team.
      </Text>
      <Text style={{ fontSize: 10, fontFamily: 'Helvetica-Bold', color: blue, marginTop: 10 }}>
        contact@ledgerhound.vip · +1 (833) 559-1334
      </Text>
      <Text style={{ fontSize: 9, color: slate600, marginTop: 4 }}>
        www.ledgerhound.vip/free-evaluation
      </Text>
    </View>

    <Footer data={data} />
  </Page>
);

// Page 7: Disclaimer
const DisclaimerPage = ({ data }: { data: ReportData }) => (
  <Page size="A4" style={s.page}>
    <Header data={data} />
    <Text style={s.h2}>Disclaimer & Legal Notice</Text>

    <Text style={{ ...s.p, lineHeight: 1.6 }}>
      This report was generated automatically by LedgerHound, a service of USPROJECT LLC. It is provided for informational purposes only and does not constitute legal, financial, or investment advice.
    </Text>
    <Text style={{ ...s.p, lineHeight: 1.6 }}>
      The analysis contained herein is based on publicly available blockchain data retrieved at the time of report generation. Blockchain data is permanent and immutable; however, the attribution of wallet addresses to known entities is based on proprietary and open-source intelligence databases that may not be comprehensive.
    </Text>
    <Text style={{ ...s.p, lineHeight: 1.6 }}>
      This automated report is not a substitute for a certified forensic investigation conducted by a qualified blockchain forensic analyst. For matters requiring court testimony, certified methodology, or regulatory compliance, a full forensic engagement is recommended.
    </Text>
    <Text style={{ ...s.p, lineHeight: 1.6 }}>
      Risk scores are generated algorithmically and should be interpreted as preliminary indicators only. A low risk score does not guarantee legitimacy, and a high risk score does not definitively indicate criminal activity.
    </Text>
    <Text style={{ ...s.p, lineHeight: 1.6 }}>
      LedgerHound and USPROJECT LLC are not law firms and do not provide legal representation. Users should consult with qualified legal counsel before taking any legal action based on the contents of this report.
    </Text>
    <Text style={{ ...s.p, lineHeight: 1.6 }}>
      By purchasing and using this report, you agree that USPROJECT LLC's liability is limited to the purchase price of the report.
    </Text>

    <View style={s.divider} />

    <View style={{ alignItems: 'center', marginTop: 20 }}>
      <Text style={{ fontSize: 12, fontFamily: 'Helvetica-Bold', color: blue, marginBottom: 8 }}>LedgerHound</Text>
      <Text style={{ fontSize: 9, color: slate600 }}>Blockchain Forensics & Crypto Asset Tracing</Text>
      <Text style={{ fontSize: 9, color: slate600, marginTop: 4 }}>USPROJECT LLC</Text>
      <Text style={{ fontSize: 9, color: slate400, marginTop: 8 }}>contact@ledgerhound.vip · www.ledgerhound.vip</Text>
      <Text style={{ fontSize: 9, color: slate400 }}>+1 (833) 559-1334</Text>
    </View>

    <Footer data={data} />
  </Page>
);

export const ReportDocument = ({ data }: { data: ReportData }) => (
  <Document>
    <CoverPage data={data} />
    <SummaryPage data={data} />
    <AnalyticsPage data={data} />
    <EntitiesPage data={data} />
    <TransactionsPage data={data} />
    <LegalPage data={data} />
    <DisclaimerPage data={data} />
  </Document>
);
